# Generated by Django 5.1.1 on 2024-09-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_alter_task_product_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='product',
            new_name='project',
        ),
    ]
